### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by J-T-McC**
PHP 8 Support

- Updated composer requirements
- Removed deprecated method
- Added test for missing coverage
- Updated types throughout
- Updated phpunitxml to support new version

CircleCI updates outstanding

### CODE REVIEW

**Comment by J-T-McC** [comment]
@estahn is there anything outstanding you would like to see that might lead to a merge here? If the PR is too far reaching I can slim it down for basic PHP 8 support. Was trying to coax a 4.0 tag.

**Comment by estahn** [comment]
> @estahn is there anything outstanding you would like to see that might lead to a merge here? If the PR is too far reaching I can slim it down for basic PHP 8 support. Was trying to coax a 4.0 tag.

@J-T-McC Sorry for the late response. I moved things over to GitHub actions. Can you update your branch with master and enable the required PHP versions?

**Comment by J-T-McC** [comment]
> > @estahn is there anything outstanding you would like to see that might lead to a merge here? If the PR is too far reaching I can slim it down for basic PHP 8 support. Was trying to coax a 4.0 tag.
> 
> @J-T-McC Sorry for the late response. I moved things over to GitHub actions. Can you update your branch with master and enable the required PHP versions?

Merged and updated

**Comment by estahn** [comment]
fixes #24

**Pull request merged**
